# Generated by Django 5.1.5 on 2025-01-29 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_details', '0002_alter_personaldetails_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isGraduate', models.BooleanField(verbose_name='Is Graduate')),
                ('startDate', models.DateField(verbose_name='Start Date')),
                ('expectedGraduateDate', models.DateField(verbose_name='Expected Graduate Date')),
                ('PersonalDetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal_details.personaldetails')),
            ],
        ),
    ]
