<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-01-30 00:37
=======
# Generated by Django 5.1.5 on 2025-01-29 16:37
>>>>>>> 39b37c98d3bc9c24d5cf7d24db19d899ee982453

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('personal_details', '0001_initial'),
=======
        ('personal_details', '0002_alter_personaldetails_profession'),
>>>>>>> 39b37c98d3bc9c24d5cf7d24db19d899ee982453
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('isGraduate', models.BooleanField(verbose_name='is graduate')),
                ('startDate', models.DateField(verbose_name='start date')),
                ('expectedGraduateDate', models.DateField(verbose_name='expected graduate date')),
=======
                ('isGraduate', models.BooleanField(verbose_name='Is Graduate')),
                ('startDate', models.DateField(verbose_name='Start Date')),
                ('expectedGraduateDate', models.DateField(verbose_name='Expected Graduate Date')),
>>>>>>> 39b37c98d3bc9c24d5cf7d24db19d899ee982453
                ('PersonalDetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal_details.personaldetails')),
            ],
        ),
    ]
