# Generated by Django 5.1.5 on 2025-01-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='expectedGraduateDate',
            field=models.DateField(verbose_name='expected graduate date'),
        ),
        migrations.AlterField(
            model_name='school',
            name='isGraduate',
            field=models.BooleanField(verbose_name='is graduate'),
        ),
        migrations.AlterField(
            model_name='school',
            name='startDate',
            field=models.DateField(verbose_name='start date'),
        ),
    ]
