# Generated by Django 5.1.5 on 2025-01-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='expectedGraduateDate',
            field=models.DateField(verbose_name='graduation complete date or expected graduate date'),
        ),
    ]
