# Generated by Django 5.1.5 on 2025-01-30 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isGraduate', models.BooleanField(verbose_name='is graduate')),
                ('startDate', models.DateField(verbose_name='start date')),
                ('expectedGraduateDate', models.DateField(verbose_name='expected graduate date')),
                ('name', models.CharField(max_length=30)),
                ('PersonalDetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal_details.personaldetails')),
            ],
        ),
    ]
