# Generated by Django 5.1.5 on 2025-01-31 17:08

import story.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='story/uploads/videos', validators=[story.models.validate_video_file]),
        ),
    ]
