# Generated by Django 5.1.5 on 2025-01-31 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('story', '0002_story_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryEmoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('like', '👍'), ('love', '❤️'), ('care', '🤗'), ('haha', '😂'), ('wow', '😮'), ('sad', '😢'), ('angry', '😡')], max_length=5)),
                ('emojier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storyEmojies', to='person.person')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storyEmojies', to='story.story')),
            ],
        ),
    ]
