# Generated by Django 5.1.5 on 2025-02-03 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
        ('person', '0002_alter_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='person.person'),
        ),
    ]
