# Generated by Django 5.1.5 on 2025-02-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_parent_comment_person_comment_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
