# Generated by Django 5.1.5 on 2025-02-03 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('personal_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presonalDetails', to='person.person'),
        ),
    ]
