# Generated by Django 5.1.5 on 2025-01-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='profession',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
