# Generated by Django 5.1.5 on 2025-01-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_details', '0002_alter_personaldetails_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='dateOfBirth',
            field=models.DateField(verbose_name='date of birth'),
        ),
    ]
