# Generated by Django 5.1.5 on 2025-02-03 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_user'),
        ('personal_details', '0002_alter_personaldetails_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personalDetails', to='person.person'),
        ),
    ]
